### ISSUE TITLE
easier install without kernel source

### ISSUE THREAD

**Issue by brendangregg** [iovisor/ply#19]
I found this works, with the kernel headers package only (Ubuntu Yakkety):

```
$ git clone https://github.com/iovisor/ply
$ cd ply
$ ./autogen.sh
$ ./configure --with-kerneldir=/usr/src/linux-headers-4.8.0-30-generic
$ make
Making all in src
make[1]: Entering directory '/root/ply/src'
  LEX      lang/lex.c
  YACC     lang/parse.c
updating lang/parse.h
  HEADERS  /usr/src/linux-headers-4.8.0-30-generic(x86_64)
make -C /usr/src/linux-headers-4.8.0-30-generic ARCH=x86_64 INSTALL_HDR_PATH=/root/ply/src/.kernel headers_install
make[2]: Entering directory '/usr/src/linux-headers-4.8.0-30-generic'
  CHK     include/generated/uapi/linux/version.h
make[3]: *** No rule to make target 'arch/x86/entry/syscalls/syscall_32.tbl', needed by 'arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h'.  Stop.
arch/x86/Makefile:191: recipe for target 'archheaders' failed
make[2]: *** [archheaders] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.8.0-30-generic'
Makefile:1089: recipe for target '.kernel/include/linux/version.h' failed
make[1]: *** [.kernel/include/linux/version.h] Error 2
make[1]: Leaving directory '/root/ply/src'
Makefile:402: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
$ vi src/Makefile
[...]
.kernel/include/linux/version.h:
    @echo "  HEADERS  /usr/src/linux-headers-4.8.0-30-generic(x86_64)"
#   make -C /usr/src/linux-headers-4.8.0-30-generic $(kernelenv) headers_install
[...]
$ make
$ sudo make install
$ ply -c 'kprobe:schedule { @cs[comm()].count(); }'
1 probe active
^Cde-activating probes

@cs:
gmain           	       1
watchdog/0      	       1
ply             	       3
kworker/0:1     	       4
kworker/u2:2    	       4
rcu_sched       	       5
iscsid          	       7
kworker/u2:0    	      10
sshd            	      10
swapper/0       	      18
```

So... Do we need the headers_install?

**Comment by wkz** [comment]
I would say, yes. This only works because `linux/version.h` is generated before the build is aborted and because `gcc` likely uses `linux/bpf.h` from your `/usr/include`. This is bad for a couple of reasons:

1) There's nothing that guarantees that the kernel's build order does not change such that the version header is not available after the job is aborted.

2) Depending on a broken build triggers my spidey sense, it _feels_ wrong.

3) Building using headers from an older kernel with just an updated `linux/version.h` seems to go against the spirit of the strict version check in the verifier.

4) Mixing headers might cause the build to fail since certain features are enabled based on the version number.

Do you know how bcc handles this issue? It seems to me that the proper solution would be to patch the kernel (or the debian packaging of linux-headers) so that one can `make headers_install` from it.

**Comment by aktau** [comment]
What I've been doing is the following (also a debian system):

```
( git clean -d -q -x -f && ./autogen.sh && ./configure CFLAGS="-I/usr/src/linux-headers-$(uname -r)/include/generated/uapi" && make )
```

The important bit being the `CFLAGS` addition. It forces `#include <kernel/version.h>` to find the one from the `linux-headers-<arch>` package instead of the one from `/usr/include`. That one defines a far more recent `KERNEL_VERSION` than my actual running kernel. Likely that has something to do with the fact that it's from the libc package:

```
dpkg -S /usr/include/linux/version.h
linux-libc-dev:amd64: /usr/include/linux/version.h
```

(My debian is sort-of a frankenstein, but at least the running kernel and kernel headers match.)

**Comment by brho** [comment]
Thanks for the hint aktau.  I'm on a debian as well.  Using the --with-kerneldir option didn't work for me (permissions issue), but your CFLAGS did.  

At least I can run a basic kprobe (kprobe:icmp_rcv), though more complex ones fail silently (kprobe:SyS_*{ @[func()].count(); }.  So maybe the header magic worked and there's another problem, or maybe there is still some underlying issue.
