### ISSUE TITLE
stack() results are unexpectedly short (on kernel 4.9.0)

### ISSUE THREAD

**Issue by aktau** [iovisor/ply#32]
Use-case: I'm trying to trace long page faults.

```
#!/usr/sbin/ply

kprobe:handle_mm_fault
{
    @lat[pid()] = nsecs();
}

kretprobe:handle_mm_fault
{
    start = @lat[pid()]; # Fetch the time at handle_mm_fault() entry.
    if (start == 0) {
        return; # Don't proveed if we don't have a start time.
    }
    lat = nsecs() - start;
    limit = 1000000;
    if (lat > limit) {
        printf("%16s(%5d): handle_mm_fault took more than %dus (%dus)", comm(), pid(), limit / 1000, lat / 1000);
        printf("%v\n\n", stack());
    }
    @lat[pid()] = nil; # Clear map.
}
```

This produces output like the following:

```
             git(191300): handle_mm_fault took more than 1000us (9121us)
	kretprobe_trampoline
	trace_page_fault+0x28

             git(191300): handle_mm_fault took more than 1000us (1524us)
	kretprobe_trampoline
	trace_page_fault+0x28

            cron(191662): handle_mm_fault took more than 1000us (1028us)
	kretprobe_trampoline
	trace_page_fault+0x28

             zsh(190053): handle_mm_fault took more than 1000us (2037us)
	kretprobe_trampoline
	__wake_up_parent
	trace_page_fault+0x28
	__wake_up_parent
	__put_user_4+0x1c
	schedule_tail+0x40
	ret_from_fork+0x8

          chrome(72654): handle_mm_fault took more than 1000us (3971us)
	kretprobe_trampoline
	trace_page_fault+0x28

            nvim(190453): handle_mm_fault took more than 1000us (2483us)
	kretprobe_trampoline
	trace_page_fault+0x28
	__clear_user+0x21
	load_elf_binary+0x12e6
	search_binary_handler+0xb8
	search_binary_handler+0xa0
	do_execveat_common.isra.37+0x5aa
	sys_execve+0x35
	kretprobe_trampoline
	return_from_SYSCALL_64
```

Sometimes the stacktrace looks like its rooted at kernel entry (`return_from_SYCALL_64`), but most of the time I only see the `kretprobe_trampoline` and `trace_page_fault`.

I'm running a Linux 4.9.0 kernel. Looking for `trace_page_fault`, I only find assembly:

```
#ifdef CONFIG_TRACING
ENTRY(trace_page_fault)
	ASM_CLAC
	pushl	$trace_do_page_fault
	jmp	error_code
END(trace_page_fault)
#endif
```

Could that be what's messing with the stack creation?

I tried running the same with `trace(8)` from bcc-tools and it appears that this is not ply's fault:

```
$ sudo trace -K -I linux/mm.h 'r::handle_mm_fault(struct vm_area_struct *vma, unsigned long address, unsigned int flags) "%d", retval'
46540   46540   chrome          handle_mm_fault  0
        kretprobe_trampoline+0x0 [kernel]
        page_fault+0x28 [kernel]

46540   46540   chrome          handle_mm_fault  0
        kretprobe_trampoline+0x0 [kernel]
        page_fault+0x28 [kernel]
```

Strangely enough, the referenced function is called `trace_fault` here, instead of `trace_page_fault`. Does `ply` have custom code to avoid printing any `trace_` prefix?

Another question/suggestions: perhaps `ply` should filter out the `kretprobe_trampoline` stuff (unless in debugging mode)?

So I guess this is just a heads up. I notice the `page_fault

Final note: non-kretprobe tracing has saner stacks:

```
$ sudo trace -K -I linux/mm.h 'p::handle_mm_fault(struct vm_area_struct *vma, unsigned long address, unsigned int flags) "%d", address
45283   45283   chrome          handle_mm_fault  72798280
        handle_mm_fault+0x1 [kernel]
        __do_page_fault+0x25c [kernel]
        page_fault+0x28 [kernel]

45283   45283   chrome          handle_mm_fault  72798280
        handle_mm_fault+0x1 [kernel]
        __do_page_fault+0x25c [kernel]
        page_fault+0x28 [kernel]
```

Although I didn't expect it to be this short, it makes ~sense.

Thanks for building a great low-dependency tool, its code is a joy to read (the parts I've seen, at least).

**Comment by alan-maguire** [comment]
I've seen some issues relating to stacks - see https://github.com/iovisor/ply/pull/35 - but more around symbol resolution. In the case of page faults I guess we'd expect a pretty short kernel stack where the page fault is triggered directly by a program (chrome in your case). I see slightly different results, likely due to different kernel versions/config options:

	kretprobe_trampoline
	do_page_fault+0x38
	page_fault+0x22	   53504

...but again the stack is short since we've trapped into kernel mode directly when we missed a memory access. So I _think_ what you're seeing makes sense (especially given how aggressive inlining of kernel functions is likely to be used in hot code paths like this) but it would probably be good to get other opinions to be sure as I'm new to ply to be honest.

**Comment by aktau** [comment]
Right, it makes sense as you say. But that's for kprobe tracing (not kretprobe) tracing. For example, I'd expect `handle_mm_fault` to always be called by `do_page_fault`, yet somehow `do_page_fault` is not in my stacks when printing the stacktrace in the kretprobe leg.

**Comment by alan-maguire** [comment]
IIRC kretprobes work something like this: on entry to the function to be traced, they replace the return address of the caller of the traced function (which is stored on the stack) with kretprobe_trampoline() - so that means when the kretprobe()ed function is done, it bounces to the kretprobe handler. When we print out the stack we see this reflected in the output. Perhaps it's possible to use knowledge of the probe point to work around this in the display of kretprobe()-recorded stacks (e.g. skip the distracting kretprobe_trampoline). But that explains why we don't see handle_mm_fault() on the stack but not why you don't see do_page_fault. I'm afraid I'm not seeing the latter problem at my end, so I'm not sure what's going on there.

**Comment by aktau** [comment]
I think it's because of kernel differences. Kernel 4.9 still has some weird trace assembly wrapping that stacks. I'm not clear why kprobe vs kretprobe would make a lot of difference here, but I'm willing to wait until I get a more modern kernel.
