### ISSUE TITLE
static linking fails

### ISSUE THREAD

**Issue by devopswise** [iovisor/ply#68]
Hello,

First, thanks for the great piece of software. I can confirm it works on (armv7l) raspberry pi zero, with kernel 5.10.
I am trying to do static linking to try it on embedded system with read-only filesystem.
I am building with:

- ./autogen.sh
- ./configure CFLAGS="-static"
- make LDFLAGS="-all-static"

and getting following linking error. Any idea how to build ply as a static library?

```
...
Making all in ply
make[3]: Entering directory '/home/pi/ply/ply/src/ply'
  CC       ply-ply.o
cd /home/pi/ply/ply/src/ply && \
/usr/bin/ld -r -b binary -o /home/pi/ply/ply/src/ply/self-test.o self-test.sh
  CCLD     ply
/usr/bin/ld: ../libply/.libs/libply.a(libply_la-provider.o): in function `provider_get':
provider.c:(.text+0xb8): undefined reference to `__start_providers'
/usr/bin/ld: provider.c:(.text+0xbc): undefined reference to `__stop_providers'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:388: ply] Error 1
make[3]: Leaving directory '/home/pi/ply/ply/src/ply'
make[2]: *** [Makefile:356: all-recursive] Error 1
make[2]: Leaving directory '/home/pi/ply/ply/src'
make[1]: *** [Makefile:457: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/ply/ply'
make: *** [Makefile:368: all] Error 2
```
[ply-complete-build-output.txt](https://github.com/iovisor/ply/files/6517237/ply-build-output.txt)

**Comment by wkz** [comment]
Finally had some time to look into this. As it turns out, the `__{start,stop}_SECTIONNAME` symbols are only emitted for shared libraries. I patched the provider stuff to use a statically allocated array instead, but unfortunately this is also used to manage all built-in functions, which is a much bigger job to fix. I am leaving this issue open, as I definitely agree that you should be able to link it statically, but it is not likely that I will fix it anytime soon.

Regarding your particular use-case: I run ply on read-only (SquashFS) filesystems all the time without issue. What is the issue there?

**Comment by devopswise** [comment]
Hi @wkz 

Thanks for update.

> Regarding your particular use-case: I run ply on read-only (SquashFS) filesystems all the time without issue. What is the issue there?
I don't want to rebuild an image, I wanted to create a static binary and copy & run it inside /tmp folder.

**Comment by wkz** [comment]
Got it. In a pinch I suppose you could:
1. Set `DESTDIR` and `make install` to an empty directory.
2. `tar` it up
3. Explode it in `/tmp` on target
4. Run ply with `/tmp/ply/lib` in your `LD_LIBRARY_PATH`
