### ISSUE TITLE
printing strings

### ISSUE THREAD

**Issue by brendangregg** [iovisor/ply#9]
```
# ply -c 'kprobe:SyS_open { printf("open %s\n", arg(0)); }'
1 probe active
open pr??
open ?q??
open ?!A
open pr??
open ?q??
```

Ok, I need to use mem(). This ticket is to explore either:

A) not needing mem(). Previous command would just work.

B) a shortcut, like:

```
# ply -c 'kprobe:SyS_open { printf("open %s\n", str(arg(0))); }'
```

where str() could be:

```
#define str(p)    (mem(p, "128s"))
```

Could also make the 128 a global tunable.

**Comment by wkz** [comment]
A) This is a tough one. ply has no information about the type of `open()`s arguments. What would be awesome is to have something equivalent to CTF, both for the kernel and for user-space programs. In the particular case of `printf()` I guess it could be inferred from the format string, but it does not help you in the case of aggregations, something like `@[pid(), arg(0)].count()`.

I do want to support debug symbols, this is especially important for `uprobe`s since there's nothing like kallsyms in that case. So if you have the debuginfo for the kernel on the system, it could be used to infer the type of arguments.

B) This is something I want to add, but not as a shortcut to `mem()`. I want it to compile to a `probe_strncpy` call in the kernel. That interface is not there yet though, its on my list to submit a patch for it.

That's because when you do a `probe_read()` you get garbage after the null byte. This means that something like: `@[mem(arg(0), "128s")].count()` will index into different buckets in the hash for the same string.

So, `str()` is coming, but I'm saving the name for the real deal :smile:
